// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:83e8cb1d-c9a4-4e94-86c0-56420cc428db",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Pb508Qmr2",
    "aws_user_pools_web_client_id": "55319db3d3hde58dkb8kognfcr"
};


export default awsmobile;
